= Enterprise Middleware Coursework - Tutorial

This tutorial guides you through the necessary preparation required to begin your Enterprise Middleware coursework.
It is very important that you have completed this and are comfortable with the example, before beginning the coursework.

== Create Accounts

_This section applies to *all students*_

To complete this coursework you will need accounts with GitHub and OpenShift.

=== GitHub
GitHub offers the Git version control system as a service.
You will use it to host your code and to make it available to the demonstrators.
GitHub is very popular in the open-source community and works best when you make your code available to others to view, clone and contribute towards.
However, given the confidential nature of your coursework, you will need to use a private repository only accessible by yourself and the demonstrators.

If you don't already have an account you will need to:

1. Go to: https://github.com/
2. Fill in your details and select "Sign up for GitHub."
3. Obtain a private repository. The steps to do this should have been provided to you already.

TIP: GitHub is a very popular service, and you are quite likely to use it in your profesional career; especially if you work with open source software in some capacity.

=== OpenShift
OpenShift is a Platform as a Service (PaaS) Cloud offered by Red Hat.
It can host many types of applications, but for this coursework you will be using it to host Java EE 6 applications on JBoss EAP.

An account with Openshift has been created for you. You should have been emailed the details of this account before the first practical session. If not, please contact Hugo Firth (h.firth@ncl.ac.uk).

Later, when you are ready to deploy to Openshift - click link:https://github.com/NewcastleComputingScience/jboss-wfk-quickstarts/tree/v2.7.0%2BNCL201617-RC1#build-and-deploy-the-quickstart---to-openshift[here]

== Environment Setup

_This section of the tutorial only applies to students working on *their own* machines, not those provided by the university!_

link:https://youtu.be/YK_YZNBz97A?t=2m25s[Tutorial Video - 2m25s]

Once you have confirmed (as mentioned above) your email address with OpenShift, you will be directed to a web page titled https://www.openshift.com/get-started["Get Started"].
On this page you will need to select the *Windows* option at the top of the page and follow the "Installing the Client Tools on Windows" instructions subsequently displayed.
Once you have completed these steps you should have successfully created an OpenShift account, installed Ruby 2.0.0 and the Openshift RHC Client Tools on your computer.

* *Setup*. When running the `rhc setup` command you will be asked for your openshift *login* and *password*. Your login details are those used to register for OpenShift. When asked to provide a namespace for your projects, you should provide your student number (e.g 100826753).

IMPORTANT: If you encounter an "Access is denied" warning when running the RubyInstaller setup program, you should copy the installer into `C:/temp`, right click the executable and select "Run as Administrator". You will be prompted for your admin password for your machine, and Ruby should then install successfully.

IMPORTANT: If you encounter a "Permission denied" warning when installing the rhc gem, you should run the Command Prompt as an administrator (right click the shortcut and select "Run As Administrator") and retry. You will be prompted for your admin password for your machine, and the rhc gem should then install successfully.

IMPORTANT: If you encounter an "Error installing rhc" when running the command `gem install rhc` you have likely installed Ruby 1.9.3. You should uninstall RubyInstaller and instead instead select one of the Ruby 2.0.0 installers from http://http://rubyinstaller.org/downloads/["RubyInstaller Downloads"].

== Run Example

Now you will run a simple example.
This example provides you with a starting point that you will build on when you come to doing the coursework.
Therefore, it is very important that you get this working and become familiar with the code.

=== Download JBoss EAP 6.4.0

_This section of the tutorial only applies to students working on *their own* machines, not those provided by the university!_

1. Go link:http://www.jboss.org/products/eap/download/[here] and click "View Older Downloads".
2. Download the zip distribution of JBoss EAP 6.4.0.GA. _Note:_ You need to make sure you use this version of JBoss EAP as this matches the version you will be using on OpenShift. You will be required to register for the https://community.jboss.org/[JBoss community] website as part of the download process.
3. Unzip JBoss EAP to somewhere on your computer.

=== Obtain the Contacts-Swagger Quickstart

_This section applies to *all students*_

link:https://youtu.be/YK_YZNBz97A?t=13m42s[Tutorial Video - 13m42s]

1. Visit the NewcastleComputingScience/jboss-wfk-quickstarts github repo release page link:https://github.com/NewcastleComputingScience/jboss-wfk-quickstarts/releases/tag/v2.7.0%2BNCL201617-RC1[here].
2. Click on the *Download ZIP* link to obtain all the Quickstarts
3. Unzip the download to somewhere on your computer. Be aware this may take some time as there are many files and you are likely writing to your (networked) `H` drive.
4. Open a terminal and go to the `contacts-swagger` directory in the quickstart bundle you just unzipped.


=== Run the Quickstart

_This section applies to *all students*_

link:https://youtu.be/YK_YZNBz97A?t=16m6s[Tutorial Video - 16m6s]

1. Step through the instructions on the Contacts-Swagger quickstart page link:https://github.com/NewcastleComputingScience/jboss-wfk-quickstarts/tree/v2.7.0%2BNCL201617-RC1/contacts-swagger[here], upto and including section "Run the Arquillian Tests". Make sure you follow the "Configure Maven" section correctly as these instructions are important.
2. Now follow the "Build and Deploy the Quickstart to OpenShift" instructions link:https://github.com/NewcastleComputingScience/jboss-wfk-quickstarts/tree/v2.7.0%2BNCL201617-RC1#build-and-deploy-the-quickstart---to-openshift[here], including all the sub-sections that take you to the end of the page.


== Eclipse Setup

_This section applies to *all students*_ 

If you are on a University machine and wish to use Eclipse to edit the contacts-swagger example (and your coursework), you should use the version of Eclipse neon provided on your uni machine.

If you are on your own machine we recommend you visit the Eclipse https://www.eclipse.org/downloads/eclipse-packages/[downloads page] and select the "Eclipse IDE for Java EE Developers" which comes with Maven support.

Regardless, once in Eclipse you must add the contacts-swagger example to your workspace using the following steps:

. *Import the maven project into eclipse*.
  .. Within a new workspace, click 'File' -> 'Import...'
  .. Select 'Maven' -> 'Existing Maven Projects'
  .. Click on 'Browse' and select the contacts-swagger quickstart folder.
  .. Click 'Finish'

TIP: You may use other IDEs or editors if you live, but we will not support their use, so be sure that they are able to import and work with Maven projects.

IMPORTANT: When you first import the project, maven will download all of the project dependencies to an `.m2` repository folder on your `H` drive. This may take a *very* long time.

== Working with Git

_This section applies to *all students*_

You will be using Git in the coursework for regular checkpoint and backup of your code to GitHub.
You will also use Git to deploy new versions of your application to OpenShift.
This section will show you how to create a copy of the 'contacts-swagger' example, ready fo you to extend in the coursework, and also how to push the code to GitHub and OpenShift.

#TODO: edit below line as it is confusing.

* Build on top of the contacts-swagger example, by moving your clone of the OpenShift git repository at contacts-swagger to some other location on your disk, where you want to develop your coursework submission.

* Now you need to be able to push your code to your git repository on GitHub. To do this, you will need the url of the private repository created earlier.

    git remote add github <private GitHub repo url>
    git push github master -f

WARNING: The -f flag for git push should not be used after this initial setup. Doing so may result in the loss of commits in the remote repository.

* When you work with Git there are often files you wish for Git to ignore and exclude from your repository. These may include confidential data or files generated by your IDE. This is achieved using a .gitignore file which specifies the files and/or directories you wish to exclude. We suggest you use the .gitignore file provided in this csc8104-assignment repository. Copy this file into your repository and commit the file using the following commands.

   git add .gitignore
   git commit -m 'Adding .gitignore file.'

TIP: If you are new to Git, you should read Pro Git.  Chapters 1-3 should cover all the functionality required for this coursework.  Available at: http://git-scm.com/book

== Viewing your datasource
During development of your application you may find it very useful to be able to inspect the contents of your database. To do this you will use h2console, which is provided as part of the quickstarts.

=== Deploying h2console

_This section of the tutorial only applies to students working on *their own* machines, not those provided by the university!_

Obtain the `h2console.war` file from link:https://github.com/jboss-developer/jboss-eap-quickstarts/tree/6.4.0.GA/h2-console[here] , copy it into the "standalone/deployments" directory of your *EAP_HOME* directory and restart your local JBoss server.

=== Accessing h2console

_This section applies to *all students*_

You can access the console at http://localhost:8080/h2console.

To log into the datasource for your application, use the following details.

    Driver Class: javax.naming.InitialContext
    JDBC URL: Your JDBC URL is available in your persistence.xml file, and can be found between the <jta-data-source> tags e.g. java:jboss/datasources/ContactsSwaggerQuickstartDS
    Username: sa
    Passowrd: sa

. Click "Test Connection" and if these details are correct you will see "Test successful".

. Press "Connect" to view the contents of the datasource.

TIP: Your persistence.xml is the configuration file used to specify the connection details to your database. Your persistence.xml file can be found in src/main/resources/META-INF.

== Testing your API

Besides the Arquillian tests run through maven, you will occasionally want to test your API in a more manual fashion, in order to clearly see what information is being sent and received.

It is partly for this purpose that the Contacts-Swagger quickstart uses the link:http://swagger.io[Swagger] tool to generate API documentation. 

Not only does Swagger use link:https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X[@Annotations] to automatically generate attractive documentation for API endpoints, but this documentation is interactive.
This allows you to run each supported http operation from the documentation webpage with sample input and see the response JSON.
An example of swagger documentation can be found link:http://petstore.swagger.io/[here].

Another common method of manual testing is of APIs is sending http requests from the command line, using a tool called link:http://curl.haxx.se/[cURL].

cURL should already be installed on your machines, if it is not, please contact the teaching staff.

To give you an example of how you might use cURL to see what your API is doing, once the QuickStart is running (locally) you could execute the following commands (in cmd.exe):

* to see a list of all contacts returned, formatted as JSON and accompanied by all HTTP headers.

    curl -v http://localhost:8080/jboss-contacts-swagger/api/contacts/

* to create a new contacts.

    curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
      \"firstName\": \"Alice\",
      \"lastName\": \"Bob\",
      \"email\": \"alice@bob.com\",
      \"phoneNumber\": \"(227) 111-1111\",
      \"birthDate\": \"1982-10-26\"
    }" "http://contacts-100937864.rhcloud.com/api/contacts"

The *-v* switch instructs curl to display all possible information, whilst the *-X* switch allows you to specify the HTTP method to be used and *-d* the data to be sent.

NOTE: In the above URLs "jboss-contacts-swagger" is the name of the deployed .war file.

TIP: If you would like to learn more about how to use cURL, you can refer to the link:http://curl.haxx.se/docs/manpage.html[official documentation] or link:http://code.tutsplus.com/tutorials/a-beginners-guide-to-http-and-rest--net-16340[this] useful tutorial.
